### ISSUE TITLE
instructions?

### ISSUE THREAD

**Issue by ZoraizQ** [phvietan/shadeless#2]
I'm getting this by adding any project info and description:
`[00] server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Average RTT: 0, Last error: connection() error occured during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }`

**Comment by phvietan** [comment]
Hi, sorry about that. Shadeless is not mature enough for production, I will definitely write instruction soon 😅

**Comment by ZoraizQ** [comment]
Thanks! No problem!
